version: "3.9"

services:
  api:
    build: .
    command: bash -lc "python -m uvicorn app.api.main:app --host 0.0.0.0 --port 8000"
    env_file: [.env]
    ports:
      - "8000:8000"
    restart: unless-stopped



  dashboard:
    build: .
    command: bash -lc "streamlit run app/dashboard/dashboard.py --server.address 0.0.0.0 --server.port 8501"
    env_file: [.env]
    environment:
      - API_BASE=http://api:8000
    ports:
      - "8501:8501"
    depends_on: [api]