GDP_METRICS = {
    "GDP_PPP_PER_CAPITA",
    "GDP_VS_CASES_PER100K_YEAR",
}

METRIC_COLUMNS = {
    "NEW_CASES": "NEW_CASES",
    "NEW_DEATHS": "NEW_DEATHS",
    "CASES_7DMA": "CASES_7DMA",
    "DEATHS_7DMA": "DEATHS_7DMA",
    "NEW_CASES_PER_100K": "NEW_CASES_PER_100K",
    "NEW_DEATHS_PER_100K": "NEW_DEATHS_PER_100K",
    "TOTAL_VACCINATIONS": "TOTAL_VACCINATIONS",
    "PEOPLE_VACCINATED": "PEOPLE_VACCINATED",
    "PEOPLE_FULLY_VACCINATED": "PEOPLE_FULLY_VACCINATED",
    "DAILY_VACCINATIONS": "DAILY_VACCINATIONS",
    "TOTAL_VACCINATIONS_PER_HUNDRED": "TOTAL_VACCINATIONS_PER_HUNDRED",
    "PEOPLE_VACCINATED_PER_HUNDRED": "PEOPLE_VACCINATED_PER_HUNDRED",
    "PEOPLE_FULLY_VACCINATED_PER_HUNDRED": "PEOPLE_FULLY_VACCINATED_PER_HUNDRED",
}
